server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: StudyConnect API
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=StudyConnect;encrypt=false;trustServerCertificate=true
    username: sa
    password: ITB123456 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

logging:
  level:
    com.studyconnect: DEBUG
    org.springframework.web: DEBUG